SELECT AccountId
		,TranDate
		,TranAmt
		,FIRST_VALUE(TranAmt) OVER(PARTITION BY AccountId ORDER BY TranDate)
		,LAST_VALUE(TranAmt) OVER(PARTITION BY AccountId ORDER BY TranDate)
		,LAST_VALUE(TranAmt) OVER(PARTITION BY AccountId
								  ORDER BY TranDate
								  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
FROM tr



LAST_VALUE(TRANAMT) OVER(PARTITION BY ACCOUNTID,
							ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING )

